format_version: v1.0
type: UniqueComponent
attributes: {id: le_gfx_intf_spi4}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: BlockingTransfers}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: DRV_SPI}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: drv_spi_0}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: drv_spi}
  - type: DirectCapability
    attributes: {id: le_gfx_intf_spi4}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: le_gfx_driver_external}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: SPI Display Interface}
- type: ElementPosition
  attributes: {x: '386', y: '445', id: le_gfx_intf_spi4}
